"""
data/vocab/vocab_loader.py — Loads curated vocabulary JSON files into the RAG dictionary

Responsibilities:
  - Load all <Language>.json files from data/vocab/ on startup
  - Pre-seed the RAGDictionary so agents have verified translations immediately
  - Provide pick_word() to select a word by language / topic / difficulty,
    so SentenceAgent asks the LLM only to write a sentence — not to invent a word

This eliminates the root cause of CJK romanization errors: the model no longer
has to supply the foreign_word or its romanization; both come from the JSON file.
"""

from __future__ import annotations

import json
import pathlib
import random
from dataclasses import dataclass
from typing import Optional

from rag.dictionary import RAGDictionary, DictionaryEntry

_VOCAB_DIR = pathlib.Path(__file__).parent


@dataclass
class VocabEntry:
    word:         str
    romanization: str   # empty string for Latin-script languages
    english:      str
    pos:          str
    difficulty:   str
    topic:        str
    language:     str


class VocabLoader:
    """
    Loads curated vocabulary JSON files and provides filtered word selection.

    Usage:
        loader = VocabLoader()
        loader.seed_rag(rag)                       # pre-populate RAG index
        entry = loader.pick_word("Japanese", "food", "beginner", seen)
    """

    def __init__(self):
        self._vocab: dict[str, list[VocabEntry]] = {}  # lang → entries
        self._load_all()

    # ── Public API ─────────────────────────────────────────────────────────────

    def seed_rag(self, rag: RAGDictionary) -> int:
        """
        Pre-populate the RAG dictionary with all loaded vocab entries.
        Returns the number of entries added.
        """
        added = 0
        for lang, entries in self._vocab.items():
            for e in entries:
                rag.add_entry(DictionaryEntry(
                    foreign_word=e.word,
                    language=lang,
                    english_meaning=e.english,
                    part_of_speech=e.pos,
                    example_context="",   # no example in the JSON; generated by LLM per sentence
                ))
                added += 1
        return added

    def pick_word(
        self,
        language:   str,
        topic:      str,
        level:      str,           # "beginner" | "intermediate" | "advanced"
        seen_words: set[str],      # words to avoid (already encountered this session)
        fallback:   bool = True,   # if True, relax filters rather than returning None
    ) -> Optional[VocabEntry]:
        """
        Pick a random word for the given language, topic, and difficulty level.

        Filtering strategy (most specific → least specific):
          1. Match language + topic + difficulty band
          2. If too few results, relax to language + difficulty band
          3. If fallback=True and still none, return any unseen word for this language
        """
        entries = self._vocab.get(language, [])
        if not entries:
            return None

        difficulty_band = _level_to_difficulty(level)

        # Filter out already-seen words
        unseen = [e for e in entries if e.word not in seen_words]
        if not unseen:
            # All words have been seen — allow repeats but still filter by difficulty
            unseen = entries

        # Step 1: topic + difficulty match
        topic_norm = topic.lower()
        candidates = [
            e for e in unseen
            if _topic_matches(e.topic, topic_norm)
            and e.difficulty in difficulty_band
        ]

        # Step 2: relax topic, keep difficulty
        if len(candidates) < 3:
            candidates = [e for e in unseen if e.difficulty in difficulty_band]

        # Step 3: fallback — any unseen word for this language
        if not candidates and fallback:
            candidates = unseen

        return random.choice(candidates) if candidates else None

    def languages(self) -> list[str]:
        return list(self._vocab.keys())

    def count(self, language: str) -> int:
        return len(self._vocab.get(language, []))

    # ── Private ────────────────────────────────────────────────────────────────

    def _load_all(self) -> None:
        for path in sorted(_VOCAB_DIR.glob("*.json")):
            lang = path.stem   # filename without extension = language name
            try:
                with open(path, encoding="utf-8") as f:
                    raw = json.load(f)
                entries = []
                for item in raw:
                    entries.append(VocabEntry(
                        word         = item["word"],
                        romanization = item.get("romanization", ""),
                        english      = item["english"],
                        pos          = item.get("pos", ""),
                        difficulty   = item.get("difficulty", "easy"),
                        topic        = item.get("topic", "everyday life"),
                        language     = lang,
                    ))
                self._vocab[lang] = entries
            except Exception as e:
                print(f"[VocabLoader] Warning: could not load {path.name}: {e}")


# ── Helpers ────────────────────────────────────────────────────────────────────

def _level_to_difficulty(level: str) -> set[str]:
    """Map user level to allowed difficulty values."""
    return {
        "beginner":     {"easy"},
        "intermediate": {"easy", "medium"},
        "advanced":     {"easy", "medium", "hard"},
    }.get(level, {"easy", "medium"})


def _topic_matches(entry_topic: str, query_topic: str) -> bool:
    """Fuzzy topic match — checks if any word in query appears in entry topic."""
    query_words = set(query_topic.replace(" and ", " ").split())
    entry_words = set(entry_topic.replace(" and ", " ").split())
    return bool(query_words & entry_words)
